title: Samuel Diethelm
description: >- # this means to ignore newlines until "baseurl:"
  Industrial Engineer - Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: samueldiethelm
github_username:  samueldiethelm
linkedin_username: samueldiethelm
google_analytics: UA-124454059-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-target-blank

show_excerpts: true
excerpt_separator: "<!--more-->"
permalink: /:year/:month/:day/:title/
timezone: Europe/Madrid

kramdown:
  input: GFM
  hard_wrap: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
